#!/bin/bash
vim client/src/config/index.js 
vim server/app/config/index.js

# server
cd server
npm i
tmux kill-session -t 9
tmux new-session -d -s 9 'nodemon index.js'
cd ..

# client
cd client
npm i
tmux new-session -d -s 8 'npm start'
#npm run build
#./deploy.sh
#cd ..

# deployserver
#cd deployServer
#npm i
#tmux kill-session -t 8
#tmux new-session -d -s 8 'node app.js'
#cd ..
